### ISSUE TITLE
External reference clock fails to be enabled

### ISSUE THREAD

**Issue by pgreenland** [myriadrf/srsRAN#2]
## Issue Description ##

enb won't start with external reference clock option provided, hanging indefinitely with the following output:

```
---  Software Radio Systems LTE eNodeB  ---

Reading configuration file enb.conf...

Built in Release mode using commit b6e9c087f on branch HEAD.

Opening 1 channels in RF device=lime with args=index=0,rxant=LNAH,txant=BAND2,cal=all,refclk=10e6
Supported RF device list: lime file
Number of requested channels: 1
Found device #0: LimeSDR-USB, media=USB 3.0, module=FX3, addr=1d50:6108, serial=000908340187372A
Reference clock 30.72 MHz
Initializing limesdr device
Setting reference clock to 10.00 MHz
```

## Setup Details ##

I'm using a LimeSDR-USB 1.4 on a Debian 11 system, with LimeSuite tag v22.09.1 and srsRAN tag release_22_04_LC01.

## Expected Behavior ##

External clock will be correctly enabled and enb startup will complete.

## Actual Behaviour ##

Red / green LED on SDR doesn't light indicating that the internal reference clock is still in use. Reference clock is working correctly when enabled via LimeSuite or LimeUtils (with the LED changing from green to red and back when the clock signal is removed and lock is lost / recovered).

## Steps to reproduce the problem ##

Run as per example configuration on [LibreCellular site](https://librecellular.org/user/configuration.html) with device line:

device_args = index=0,rxant=LNAH,txant=BAND2,cal=all,refclk=10e6

## Additional Information ##

I believe I've identified the problem and found for me a solution.

The refclk argument caused the lime srsRAN driver (lib/src/phy/rf/rf_lime_imp.c) to call to LMS_SetClockFreq (src/API/lms7_api.cpp) of the API.

Which in turn calls SetClkFreq on an LMS7_Device instance (src/API/lms7_device.cpp).

This function contains the following sequence:

```
lime::ADF4002 module;
module.SetDefaults();
double fvco = lms->GetReferenceClk_SX(lime::LMS7002M::Rx);
int dummy;
module.SetFrefFvco(freq/1e6, fvco/1e6, dummy, dummy);
```

I believe the problem lies in the constructor of src/ADF4002/ADF4002.cpp which calls CalculateRN.

CalculateRN uses the member variables txtFref and txtFvco to compute some floating point variables which are used as loop exit conditions.

The two member variables txtFref and txtFvco appear to be uninitialised. A printf added before the entry to the loop, shows that more often than not one or both of these are nan and as such will never be zero, leading to an infinite loop.

I've fixed it by simply initialising the variables to zero before calling CalculateRN, or just commenting out the CalculateRN function in setDefaults, as it'll be called immediately after by SetFrefFvco.

The issue likely exists in the LimeSuite repo itself, although there's a subtle difference in LimeUtils which uses the new operator rather than allocating the ADF4002 object on the stack. I don't believe new initialised the allocate RAM to zero (it might?) otherwise I suspect this tool is just getting lucky after the OS clears it a block of RAM for the heap.

Wasn't sure where the best place to raise a ticket was, can raise in LimeSuite as well if needed?

-----

@9600 Amazing work on the LibreCellular site btw! I found it while trawling the MyriadRF Discourse, you should publicise it more heavily. I've spent the last week or so setting up a used LimeSDR-USB for LTE simulation. I'd just about bumbled my way through understanding each of the libraries, programming a sim card and getting it limping into life when I found your step by step guide. A virtual carbon copy of my own hardware setup and guide I'd been writing myself. If only I'd found it sooner.

Running over RF cables a Ryzen 1700 is currently managing a 100PRB config, with 72Mbps DL and 50Mbps uplink as measured with iperf. MIMO was also a breeze to enable, with 2 x 50PRB again providing 72Mbps of DL with 20Mbps of uplink. Next is carrier aggregation which is looking pretty doable with two cells starting on their respective SDR channels. Although my RF setup may need a bit of work....and I think there may be another bug incoming.

**Comment by 9600** [comment]
@pgreenland Many thanks for the issue report and also the kind word; it's great to hear that the LibreCellular documentation has proved useful. 

> Wasn't sure where the best place to raise a ticket was, can raise in LimeSuite as well if needed?

If you could and also please reference this ticket it would be much appreciated.

**Comment by 9600** [comment]
@pgreenland I wondered if you'd had opportunity to test with the fix applied in Lime Suite and we could now close this issue?

**Comment by pgreenland** [comment]
Sorry my bad, working well with the recent changes to LimeSuite.

Thanks for the fast turnaround!
